modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mediaworks"
version = "${version}"
displayName = "Mediaworks"
logoFile = "icon.png"
authors = "artynova"
description = '''
Hex Casting addon themed around Media utilities and manipulation.
'''

[[dependencies.mediaworks]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mediaworks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mediaworks]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.85,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mediaworks]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.10.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mediaworks]]
modId = "moreiotas"
mandatory = false
versionRange = "[0.0.4,)"
ordering = "NONE"
side = "BOTH"
