modLoader = "javafml"
loaderVersion = "[${forgeVersion},)"
issueTrackerURL = "${modIssueTracker}"
license = "${modLicense}"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
logoFile = "icon.png"
authors = "${modAuthor}"
description = "${modDescription}"
displayURL = "${modPage}"
displayTest = "${modForgeDisplayTest}"

[[dependencies.${ modId }]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "hexcasting"
mandatory = true
versionRange = "[${hexcastingVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "geckolib3"
mandatory = true
versionRange = "[${geckolibVersion},)"
ordering = "NONE"
side = "BOTH"

